### ISSUE TITLE
Solicitud para colaboracion

### ISSUE THREAD

**Issue by GinoSalazarVillena** [pabpobar/Taller-Git-GitHub#20]
GinoSalazarVillena

**Comment by GinoSalazarVillena** [comment]
Solicito acceso para realizar taller, por favor.
Mi nombre de usuario es: GinoSalazarVillena

**Comment by pabpobar** [comment]
Aún no recibes la invitación? figura está enviada......

**Comment by pabpobar** [comment]
> Solicito acceso para realizar taller, por favor.
> Mi nombre de usuario es: GinoSalazarVillena

Tu invitación fue enviada hace bastante rato.... ¿Qué pasa?
esta es: https://github.com/pabpobar/Taller-Git-GitHub/invitations
